"""
inference.py — HuggingFace inference + Google Colab training notebook generator
"""
import json, re, requests, textwrap
from core import HF_TOKEN

HF_API = "https://api-inference.huggingface.co/models"

# ── Inference ───────────────────────────────────────────────────────
def call_hf(repo_id: str, prompt: str, hf_token: str = None,
            max_new: int = 512, temperature: float = 0.7) -> str:
    """Call any HuggingFace model by repo_id with optional user-supplied token."""
    token   = hf_token or HF_TOKEN
    headers = {"Authorization": f"Bearer {token}"}
    payload = {
        "inputs": prompt,
        "parameters": {"max_new_tokens": max_new, "temperature": temperature,
                       "return_full_text": False},
    }
    try:
        r = requests.post(f"{HF_API}/{repo_id}", headers=headers, json=payload, timeout=60)
        r.raise_for_status()
        result = r.json()
        if isinstance(result, list) and result:
            return result[0].get("generated_text", "").strip()
        if isinstance(result, dict) and "generated_text" in result:
            return result["generated_text"].strip()
        return str(result)
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 503:
            return "[MODEL_LOADING] Model is warming up — try again in 20 seconds."
        return f"[HTTP {e.response.status_code}] {e}"
    except Exception as e:
        return f"[ERROR] {e}"

def call_gemby(prompt: str) -> str:
    """Default: use Gemby Agent 3B."""
    return call_hf("Hwiiiiiiii/gemby-agent-3b", prompt)

def generate_dataset_rows(topic: str, num_rows: int,
                          columns: list, style: str,
                          model_repo: str = None,
                          user_hf_token: str = None,
                          progress_cb=None) -> list:
    repo = model_repo or "Hwiiiiiyyy/gemby-agent-3b"
    rows = []
    col_str = ", ".join(columns)
    for i in range(num_rows):
        if progress_cb:
            progress_cb(i, num_rows)
        prompt = (
            f"Generate ONE realistic row for a {style} dataset about: {topic}.\n"
            f"Columns: {col_str}\n"
            f"Row {i+1}/{num_rows}.\n"
            f"Respond ONLY with a JSON object using exactly these keys: "
            + "{ " + ", ".join(f'"{c}": "..."' for c in columns) + " }"
        )
        raw = call_hf(repo, prompt, hf_token=user_hf_token)
        try:
            m   = re.search(r'\{.*?\}', raw, re.DOTALL)
            row = json.loads(m.group()) if m else {c: f"sample_{i+1}" for c in columns}
        except Exception:
            row = {c: f"sample_{i+1}" for c in columns}
        rows.append(row)
    return rows

# ── Colab notebook generator ─────────────────────────────────────────
COLAB_TEMPLATE = """
{{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {{
    "colab": {{
      "provenance": [],
      "gpuType": "T4"
    }},
    "kernelspec": {{
      "name": "python3",
      "display_name": "Python 3"
    }},
    "accelerator": "GPU"
  }},
  "cells": [
    {{
      "cell_type": "markdown",
      "metadata": {{}},
      "source": [
        "# 🤖 Train: {model_name}\\n",
        "Auto-generated by **Gemby Platform**\\n",
        "Base model: `{base_model}`\\n",
        "Dataset: {dataset_rows} rows · {num_cols} columns"
      ]
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── Install dependencies\\n",
        "!pip install -q transformers datasets peft trl accelerate bitsandbytes huggingface_hub"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── Config — fill in your tokens\\n",
        "HF_TOKEN       = \\"{hf_token}\\"   # Your HuggingFace write token\\n",
        "BASE_MODEL     = \\"{base_model}\\"\\n",
        "OUTPUT_REPO    = \\"{output_repo}\\"  # username/model-name to push to\\n",
        "EPOCHS         = {epochs}\\n",
        "LEARNING_RATE  = {lr}\\n",
        "MAX_LENGTH     = {max_length}\\n",
        "BATCH_SIZE     = {batch_size}"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "import json, torch\\n",
        "from datasets import Dataset\\n",
        "from transformers import (AutoTokenizer, AutoModelForCausalLM,\\n",
        "                          TrainingArguments, BitsAndBytesConfig)\\n",
        "from peft import LoraConfig, get_peft_model\\n",
        "from trl import SFTTrainer\\n",
        "from huggingface_hub import login\\n",
        "\\n",
        "login(HF_TOKEN)\\n",
        "\\n",
        "# ── Load dataset\\n",
        "raw = {dataset_json}\\n",
        "\\n",
        "def format_row(row):\\n",
        "    parts = [f\\\"{{k}}: {{v}}\\\" for k,v in row.items()]\\n",
        "    return {{\\\"text\\\": \\\" | \\\".join(parts)}}\\n",
        "\\n",
        "ds = Dataset.from_list([format_row(r) for r in raw])"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── Load base model (4-bit quantized)\\n",
        "bnb_cfg = BitsAndBytesConfig(load_in_4bit=True,\\n",
        "                              bnb_4bit_quant_type='nf4',\\n",
        "                              bnb_4bit_compute_dtype=torch.float16)\\n",
        "\\n",
        "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)\\n",
        "tokenizer.pad_token = tokenizer.eos_token\\n",
        "\\n",
        "model = AutoModelForCausalLM.from_pretrained(\\n",
        "    BASE_MODEL,\\n",
        "    quantization_config=bnb_cfg,\\n",
        "    device_map='auto',\\n",
        "    trust_remote_code=True\\n",
        ")"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── LoRA fine-tuning config\\n",
        "lora_cfg = LoraConfig(\\n",
        "    r=16, lora_alpha=32,\\n",
        "    target_modules=['q_proj','v_proj'],\\n",
        "    lora_dropout=0.05, bias='none',\\n",
        "    task_type='CAUSAL_LM'\\n",
        ")\\n",
        "model = get_peft_model(model, lora_cfg)\\n",
        "model.print_trainable_parameters()"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── Train\\n",
        "args = TrainingArguments(\\n",
        "    output_dir='./output',\\n",
        "    num_train_epochs=EPOCHS,\\n",
        "    per_device_train_batch_size=BATCH_SIZE,\\n",
        "    learning_rate=LEARNING_RATE,\\n",
        "    fp16=True, logging_steps=10,\\n",
        "    save_strategy='epoch',\\n",
        "    push_to_hub=True, hub_model_id=OUTPUT_REPO\\n",
        ")\\n",
        "\\n",
        "trainer = SFTTrainer(\\n",
        "    model=model, tokenizer=tokenizer,\\n",
        "    train_dataset=ds,\\n",
        "    dataset_text_field='text',\\n",
        "    max_seq_length=MAX_LENGTH,\\n",
        "    args=args\\n",
        ")\\n",
        "trainer.train()"
      ],
      "execution_count": null,
      "outputs": []
    }},
    {{
      "cell_type": "code",
      "metadata": {{}},
      "source": [
        "# ── Push to HuggingFace Hub\\n",
        "trainer.push_to_hub()\\n",
        "print(f'✅ Model pushed to https://huggingface.co/{{OUTPUT_REPO}}')"
      ],
      "execution_count": null,
      "outputs": []
    }}
  ]
}}
"""

def generate_colab_notebook(model_name: str, base_model: str,
                            output_repo: str, dataset_rows: list,
                            hf_token: str = "",
                            epochs: int = 3, lr: float = 2e-4,
                            max_length: int = 512, batch_size: int = 4) -> str:
    """Returns a .ipynb JSON string ready to open in Google Colab."""
    dataset_json = json.dumps(dataset_rows[:500], indent=2)  # cap to 500 rows in nb
    nb = COLAB_TEMPLATE.format(
        model_name    = model_name,
        base_model    = base_model,
        output_repo   = output_repo,
        hf_token      = hf_token or "YOUR_HF_WRITE_TOKEN",
        dataset_rows  = len(dataset_rows),
        num_cols      = len(dataset_rows[0]) if dataset_rows else 0,
        dataset_json  = dataset_json,
        epochs        = epochs,
        lr            = lr,
        max_length    = max_length,
        batch_size    = batch_size,
    )
    return nb
