-- Supabase schema for Asian Inference.
-- Run this once in the Supabase SQL editor.
-- The table names below match SUPABASE_APP_PREFIX = "ai".

create table if not exists public.chat_memories (
    id bigint generated by default as identity primary key,
    user_email text not null,
    role text not null check (role in ('user', 'bot')),
    content text not null,
    offer jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_chat_memories_user_created_at
    on public.chat_memories (user_email, created_at, id);

create table if not exists public.ai_users (
    email text primary key,
    name text not null default '',
    pw_hash text not null,
    plan text not null default 'starter',
    tokens integer not null default 0,
    flagged boolean not null default false,
    flag_reason text not null default '',
    platform_api_key text,
    traakteer_id text not null default '',
    stripe_customer_id text,
    stripe_subscription_id text,
    created text,
    updated text,
    last_reset text
);

create table if not exists public.ai_datasets (
    id text primary key,
    owner text not null references public.ai_users(email) on delete cascade,
    name text not null,
    description text not null default '',
    rows jsonb not null default '[]'::jsonb,
    row_count integer not null default 0,
    public boolean not null default false,
    tags jsonb not null default '[]'::jsonb,
    downloads integer not null default 0,
    likes integer not null default 0,
    storage_backend text not null default 'local',
    storage_repo text,
    storage_path text,
    created text,
    updated text
);

create index if not exists idx_ai_datasets_owner on public.ai_datasets (owner);
create index if not exists idx_ai_datasets_public on public.ai_datasets (public);

create table if not exists public.ai_models (
    id text primary key,
    owner text not null references public.ai_users(email) on delete cascade,
    name text not null,
    description text not null default '',
    base_model text not null,
    hf_repo text not null default '',
    public boolean not null default false,
    tags jsonb not null default '[]'::jsonb,
    status text not null default 'ready',
    downloads integer not null default 0,
    likes integer not null default 0,
    created text,
    updated text
);

create index if not exists idx_ai_models_owner on public.ai_models (owner);
create index if not exists idx_ai_models_public on public.ai_models (public);

create table if not exists public.ai_api_keys (
    id text primary key,
    user_email text not null references public.ai_users(email) on delete cascade,
    label text not null,
    key_value text not null,
    uses integer not null default 0,
    last_used text,
    created_at text
);

create index if not exists idx_ai_api_keys_user on public.ai_api_keys (user_email);

create table if not exists public.ai_support_tickets (
    id text primary key,
    user_email text not null references public.ai_users(email) on delete cascade,
    subject text not null,
    message text not null,
    status text not null default 'open',
    admin_reply text not null default '',
    created_at text
);

create index if not exists idx_ai_support_tickets_user on public.ai_support_tickets (user_email);
create index if not exists idx_ai_support_tickets_status on public.ai_support_tickets (status);

create table if not exists public.ai_token_logs (
    id bigint generated by default as identity primary key,
    user_email text not null references public.ai_users(email) on delete cascade,
    delta integer not null,
    reason text not null default '',
    balance integer not null,
    created_at text
);

create index if not exists idx_ai_token_logs_user on public.ai_token_logs (user_email, created_at);

create table if not exists public.ai_billing_events (
    id bigint generated by default as identity primary key,
    user_email text not null,
    event_type text not null,
    details jsonb not null default '{}'::jsonb,
    created_at text
);

create index if not exists idx_ai_billing_events_user on public.ai_billing_events (user_email, created_at);

create table if not exists public.ai_processed_webhooks (
    event_id text primary key,
    provider text not null,
    created_at text
);

create table if not exists public.ai_announcements (
    id integer primary key,
    message text not null default '',
    author text not null default '',
    active boolean not null default false,
    created_at text,
    updated_at text,
    constraint ai_announcements_singleton check (id = 1)
);

create table if not exists public.ai_auth_sessions (
    token_hash text primary key,
    user_email text not null references public.ai_users(email) on delete cascade,
    created_at text,
    expires_at text,
    last_seen_at text
);

create index if not exists ai_auth_sessions_user_idx
    on public.ai_auth_sessions (user_email, expires_at desc);

-- RLS guidance (documentation only; this file never changes policies).
-- Case 1: Secret/service-role key on a trusted server: keep the key server-side,
-- never expose it in a browser or repository. It bypasses RLS; use application
-- authorization and restrict access to Streamlit secrets. No RLS SQL is needed.
-- Case 2: Anon/publishable key: reads AND writes are subject to RLS. A 200 []
-- response can mean a SELECT policy hid the row, even after a successful POST.
-- Design and audit per-table SELECT, INSERT, UPDATE and DELETE policies (including
-- chat_memories and ai_auth_sessions), and verify with scripts/check_supabase.py
-- --write-test. This app sends the project key, not per-user Supabase JWTs, so
-- auth.uid() is not an app user identity. Do NOT add broad public policies for
-- credential/session tables; prefer a server-only secret key for this design.
